[package]
name = "gray"
version = "0.1.0"
edition = "2018"

[dependencies]
minifb = "0.20"
glam = "0.20.2"
rand_distr = "0.4.2"

[dependencies.rand]
version = "0.8.4"
default-features = false
features = ["small_rng"]
